---
- name: restart haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
    enabled: true

- name: restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
