---
ansible_connection: ssh
ansible_user: "{{ lookup('hashi_vault', 'secret=ansible/data/auth:ansible_user') }}"
ansible_ssh_pass: "{{ lookup('hashi_vault', 'secret=ansible/data/auth:ansible_ssh_pass') }}"
ansible_become: true
ansible_hashi_vault_auth_method: userpass
