---
mysql_root_password: "{{ lookup('hashi_vault', 'secret=ansible/data/mariadb:root_password') }}"
mysql_root_user: "{{ lookup('hashi_vault', 'secret=ansible/data/mariadb:root_user') }}"

mariadb_replication_enabled: True
balancer_present: True


mysql_users:
  - username: testuser1
    password: "{{ lookup('hashi_vault', 'secret=ansible/data/mariadb:testuser1_password') }}"
    host: "%"
    grants: "ALL"
    databases:
      - test1
      - test3
      - test4
  - username: testuser3
    password: "{{ lookup('hashi_vault', 'secret=ansible/data/mariadb:testuser3_password') }}"
    grants: "ALL"
    host: "%"
    databases:
      - make1

mysql_repl_user:
  - name: repl
    password: "{{ lookup('hashi_vault', 'secret=ansible/data/mariadb:replica_user_password') }}"

mysql_deleted_users:
  # key = username, value = host
  - testuser3: "%"

### mariadb config
log_basename: master1
mysql_data_dir: /var/lib/mysql

mysql_repl_master: 192.168.5.5

# haproxy configs
haproxy_user: haproxy
haproxy_user_group: haproxy
haproxy_log_path: /var/log/haproxy
