---
- name: add yum repo
  ansible.builtin.template:
    src: MariaDB.repo
    dest: /etc/yum.repos.d/
    mode: 644

- name: add epel-release
  ansible.builtin.yum:
    name: epel-release
    state: present
    update_cache: true 
    
- name: install mysql
  ansible.builtin.yum:
    name: 
    - MariaDB-client-11.0.1-1.el7.centos.x86_64
    - MariaDB-server-11.0.1-1.el7.centos.x86_64
    state: present
    update_cache: true

