---
users_present:
  - username: test_user1
    password_hash: "{{ lookup('hashi_vault', 'secret=ansible/data/linux_users_secrets:test_user1_pass') }}"
    ssh_pub_keys: 
      - "{{ lookup('hashi_vault', 'secret=ansible/data/linux_users_secrets:test_user1_pub_key') }}"
    groups:
      - group1
      - group2

  - username: test_user2
    password_hash: "{{ lookup('hashi_vault', 'secret=ansible/data/linux_users_secrets:test_user2_pass') }}"
    ssh_pub_keys:
      - "{{ lookup('hashi_vault', 'secret=ansible/data/linux_users_secrets:test_user2_pub_key') }}"
    groups:
      - group3
      - group4

users_absent:
  - testuser3

groups_absent:
  - test_group3
